### ISSUE TITLE
Correcciones en readme de backend

### ISSUE THREAD

**Issue by earias08** [EzequielMassa/AlAngulo#42]
**Proceso**
Al ingresar al repositorio de backend

**Resultado esperado**
visualizar el readme del backend, este debe contener una descripción breve del proyecto, se puede incluir ademas las librerias utilizadas, pasos para probar el proyecto, los integrantes del mismo.

**Resultado actual**
El readme solo contiene información de las queries que se pueden realizar con el proyecto, ademas expone información sensible como los tokens que no deberian quedar publicados. Si se quiere agregar la documentación de las queries sugiero por ejemplo usar una herramienta como postman para documentar las consultas, por ej: [documentar con postman](https://dev.to/juangaj07538514/documentacion-de-api-rest-con-postman-59o8)

**Captura**
![image](https://github.com/EzequielMassa/AlAngulo/assets/18445151/2f701613-1621-4932-b981-bbadb834b56f)

**Comment by EzequielMassa** [comment]
Actualizado el readme con las sugerencias.
![Captura de pantalla 2024-05-07 195512](https://github.com/EzequielMassa/AlAngulo/assets/94617066/a8b62edb-619f-41cd-8fa4-c8ce7db6878e)
