### ISSUE TITLE
Error en la reservad de una cancha

### ISSUE THREAD

**Issue by earias08** [EzequielMassa/AlAngulo#43]
Proceso
Al ingresar a la página de reservas y seleccionar fecha, cancha y horario, sin estar logueados.

Resultado esperado
visualizar un mensaje para advertir al usuario loguearse para poder reservar una cancha

Resultado actual
Al realizar los pasos de la reserva, sin estar logueados, solo se ve un mensaje de error, pero no se especifica que error ocurrio. 

Captura
![image](https://github.com/EzequielMassa/AlAngulo/assets/18445151/8b16ca61-84f3-440b-bab3-8dd779eb385c)

**Comment by EzequielMassa** [comment]
El error mencionado es de otro proyecto , en el nuestro al no estar logueado no es posible reservar cancha ya que aparece boton de "iniciar sesion" en su lugar.
![Captura de pantalla 2024-05-07 135929](https://github.com/EzequielMassa/AlAngulo/assets/94617066/6e2a03b2-8836-41fa-9de9-529115afcd0a)
![Captura de pantalla 2024-05-07 195942](https://github.com/EzequielMassa/AlAngulo/assets/94617066/6dedb692-7141-4bce-bfb9-169fbd6e7e82)
